trigger:
  schedule:
    interval: 10s

input:
  http:
    request:
      host: localhost
      port: 9200
      path: /_cluster/health

condition:
  compare:
    ctx.payload.status:
      not_eq: green

actions:
  mylog:
    logging:
      text: Cluster status is {{ ctx.payload.status }}