metadata:
  foo: abcde
  bar: 1

trigger:
  schedule:
    cron: '@every 10s'

input:
  chain:
    inputs:
    - http:
        request:
          host: localhost
          port: 9200
          method: GET
    - transform:
        script:
          id: hello
          params:
            username: uphy
    - search:
        request:
          body:
            query:
              match_all: {}
            size: 0
          indices:
          - "<metricbeat-6.3.2-{now-1h}>"
          - "<metricbeat-6.3.2-{now}>"
    - transform:
        script: |
          ctx.payload

condition:
  compare:
    ctx.payload.hits.total:
      gte: 10
  script:
    lang: javascript
    params: null
    source: |
      ctx.payload.hits.total > 100

transform:
  chain:
    inputs:
    - search:
        request:
          body:
            query:
              match_all: {}
            size: 0
          indices:
          - "*"
    - transform:
        script: |
          ctx.payload

actions:
  my-logging-action:
    throttle_period: 10m
    condition:
      script:
        lang: javascript
        params: null
        source: "true"
    logging:
      text: There are {{ ctx.payload.hits.total }} documents in your index. Threshold is 10.
  my-greeting:
    throttle_period: 10m
    condition:
      script:
        lang: javascript
        params: null
        source: "true"
    logging:
      text:
        id: template1
        params:
          username: uphy