trigger:
  schedule:
    interval: 10s

input:
  chain:
    inputs:
    - searchevents:
        condition:
          never:
        search:
          request:
            indices:
            - "<metricbeat-*-{now-3h}>"
            - "<metricbeat-*-{now}>"
            body:
              size: 0
              query:
                bool:
                  filter:
                  - range:
                      "@timestamp":
                        gte: "now-1h"
                  - match:
                      "metricset.module": system
                  - match:
                      "metricset.name": cpu
              aggs:
                group_by_host:
                  terms:
                    field: beat.hostname
                    size: 100
                  aggs:
                    cpu:
                      avg:
                        field: system.cpu.total.pct
    - searchevents:
        simple:
          _shards:
            failed: 0
            skipped: 0
            successful: 10
            total: 10
          aggregations:
            group_by_host:
              buckets:
              - cpu:
                  value: 0.20559346271705822
                doc_count: 979
                key: host1-prod
              - cpu:
                  value: 0.90591940501949321
                doc_count: 979
                key: host2-dev
              - cpu:
                  value: 0.95010493919505892
                doc_count: 979
                key: host3-prod
              doc_count_error_upper_bound: 0
              sum_other_doc_count: 0
          hits:
            hits: []
            max_score: 0
            total: 979
          timed_out: false
          took: 14
          
    - splitevents:
        transform:
          script: |
            split(ctx.payload.searchevents.aggregations.group_by_host.buckets.map(function(b) {
              return {
                _key: b.key,
                cpu: b.cpu.value,
                host: b.key
              }
            }));
transform:
  script: |
    String.prototype.endsWith = function(suffix){
      return this.indexOf(suffix, this.length - suffix.length) !== -1;
    }
    var email = ["dev@example.com"]
    if (ctx.payload.host.endsWith("-prod")) {
      email.push("prod@example.com");
    }
    ctx.payload.email = email;
    ctx.payload

actions:
  log:
    throttle_period: 1m
    condition: 
      compare:
        ctx.payload.cpu:
          gt: 0.9
    logging:
      text: |
        High CPU Usage
        Host: {{ ctx.payload.host }}
        CPU: {{ ctx.payload.cpu }}
        Detail: {{#toJson}}ctx.payload{{/toJson}}
        ---
  email:
    send_email:
      dryrun: true
      email:
        account: test
        from: "me@example.com"
        to:
        - "to1@example.com"
        - "to2@example.com"
        subject: "alert!!!"
        body: "something happened."
